/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativelib_AwesomeLib */

#ifndef _Included_nativelib_AwesomeLib
#define _Included_nativelib_AwesomeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativelib_AwesomeLib
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativelib_AwesomeLib_nativeMethod
  (JNIEnv *, jobject);

/*
 * Class:     nativelib_AwesomeLib
 * Method:    getRandom
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nativelib_AwesomeLib_getRandom
  (JNIEnv *, jobject);

/*
 * Class:     nativelib_AwesomeLib
 * Method:    printMatrix
 * Signature: ([[F)V
 */
JNIEXPORT void JNICALL Java_nativelib_AwesomeLib_printMatrix
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     nativelib_AwesomeLib
 * Method:    runJavaCodeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativelib_AwesomeLib_runJavaCodeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
